### ISSUE TITLE
Clarification on event simulator parameter changes frequency in event data generation

### ISSUE THREAD

**Issue by W-Shuoyan** [DachunKai/EvTexture#20]
Hello!

Thank you for providing the [DataPreparation.md](https://github.com/DachunKai/EvTexture/blob/main/datasets/DataPreparation.md) guide! It's an excellent resource for simulating and generating event voxels. However, I have some confusion regarding `Step 1: Event data generation`. Specifically, I would like to understand how frequently the parameters of the event simulator are randomized. Do these parameters change each time an entire video sequence is processed, every time a partial frame of the video sequence is processed, or perhaps in some other way?

I appreciate your assistance and look forward to your response. Thanks!

**Comment by DachunKai** [comment]
@W-Shuoyan Hi, for each video that requires event simulation, the random numbers Cp and Cn are generated once. This means that each simulated video has a unique random threshold. Thank you for your interest in our work.
