### ISSUE TITLE
What is the resolution this can upscale?

### ISSUE THREAD

**Issue by FurkanGozukara** [DachunKai/EvTexture#4]
Before spending my time on this to make it installed and run can you tell me? What is the resolution?

Like can we upscale 512x512 video to 1024x1024 or 2048x2048?

thank you

**Comment by FurkanGozukara** [comment]
awesome so it can upscale 512x512 into 2048x2048 right?

**Comment by DachunKai** [comment]
Sure, it can upscale a 512x512 video to 2048x2048, but it might consume a lot of GPU memory. Thanks.

**Comment by FurkanGozukara** [comment]
awesome ty. memory not important people can even rent A100 as long as you are doing optimization and not using unnecessary VRAM :D
